github_checks:
  annotations: true

coverage:
  range: 80..100
  round: down
  precision: 2

  status:
    project:
      default:
        enabled: no
        target: 80%
        threshold: 0.5%
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        enabled: no
        target: 80%
        threshold: 10%
